"""add product availability fields and orderitem snapshots

Revision ID: 08b7df495ca9
Revises: a316633fb929
Create Date: 2025-10-01 19:13:45.337414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b7df495ca9'
down_revision: Union[str, Sequence[str], None] = 'a316633fb929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('product_name', sa.String(length=200), nullable=False))
    op.add_column('order_item', sa.Column('product_sku', sa.String(length=64), nullable=True))
    op.add_column('order_item', sa.Column('unit', sa.String(length=20), nullable=False))
    op.alter_column('order_item', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_constraint(op.f('order_item_product_id_fkey'), 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    op.add_column('product', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('sku', sa.String(length=64), nullable=True))
    op.add_column('product', sa.Column('available_today', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('available_from', sa.Date(), nullable=True))
    op.add_column('product', sa.Column('can_backorder', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_product_external_id'), 'product', ['external_id'], unique=False)
    op.create_unique_constraint(None, 'product', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_index(op.f('ix_product_external_id'), table_name='product')
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'can_backorder')
    op.drop_column('product', 'available_from')
    op.drop_column('product', 'available_today')
    op.drop_column('product', 'sku')
    op.drop_column('product', 'external_id')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key(op.f('order_item_product_id_fkey'), 'order_item', 'product', ['product_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.alter_column('order_item', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order_item', 'unit')
    op.drop_column('order_item', 'product_sku')
    op.drop_column('order_item', 'product_name')
    # ### end Alembic commands ###
