"""remove available and can_backorder column

Revision ID: 0993d54d7457
Revises: 08b7df495ca9
Create Date: 2025-10-01 19:23:19.209622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0993d54d7457'
down_revision: Union[str, Sequence[str], None] = '08b7df495ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'available_today')
    op.drop_column('product', 'can_backorder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('can_backorder', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('available_today', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
