"""update tables

Revision ID: a316633fb929
Revises: f41dfd2c9d36
Create Date: 2025-09-28 16:45:18.490468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a316633fb929'
down_revision: Union[str, Sequence[str], None] = 'f41dfd2c9d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telegram_id', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'COURIER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.add_column('courier', sa.Column('users_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('courier_phone_key'), 'courier', type_='unique')
    op.create_unique_constraint(None, 'courier', ['users_id'])
    op.create_foreign_key(None, 'courier', 'users', ['users_id'], ['id'], ondelete='CASCADE')
    op.drop_column('courier', 'is_active')
    op.drop_column('courier', 'phone')
    op.drop_column('courier', 'full_name')
    op.drop_column('courier', 'created_at')
    op.add_column('customer', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('customer_phone_key'), 'customer', type_='unique')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_unique_constraint(None, 'customer', ['user_id'])
    op.create_foreign_key(None, 'customer', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('customer', 'email')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'full_name')
    op.drop_column('customer', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('customer', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='unique')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_unique_constraint(op.f('customer_phone_key'), 'customer', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('customer', 'user_id')
    op.add_column('courier', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('courier', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('courier', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('courier', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courier', type_='foreignkey')
    op.drop_constraint(None, 'courier', type_='unique')
    op.create_unique_constraint(op.f('courier_phone_key'), 'courier', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('courier', 'users_id')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
