"""remove extra column in address model

Revision ID: d841f0e7d13c
Revises: 0993d54d7457
Create Date: 2025-10-02 14:48:32.567322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd841f0e7d13c'
down_revision: Union[str, Sequence[str], None] = '0993d54d7457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'lon')
    op.drop_column('address', 'label')
    op.drop_column('address', 'lat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
